Repository googleapis/google-cloud-cpp-spanner, pull requests merged in 2019-06, with the labels that each got.

#47 Simplify WORKSPACE file.
  WORKSPACE
  bazel/google_cloud_cpp_spanner_deps.bzl
  bazel/googleapis.BUILD
  google/cloud/spanner/BUILD
Labels: cla: yes, type: cleanup

#45 Install Bazel as part of the Docker image.
  ci/install-bazel.sh
  ci/kokoro/Dockerfile.ubuntu
  ci/kokoro/build-docker.sh
Labels: cla: yes

#48 Add guidelines for using Doxygen.
  doc/doxygen-style-guide.md
Labels: cla: yes

#37 Fix a few shellcheck warnings in the ci scripts.
  ci/install-retry.sh
  ci/kokoro/build-docker.sh
  ci/kokoro/docker/build.sh
Labels: cla: yes

#38 Implements spanner::Value skeleton with support for BOOL, INT64, FLOAT64, and STRING
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#55 Refactoring to make it easier to add spanner ARRAY support.
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#56 Removed dep on GCS.
  bazel/google_cloud_cpp_spanner_deps.bzl
  google/cloud/spanner/BUILD
  google/cloud/spanner/spanner_tool.cc
Labels: cla: yes

#58 Adds support for spanner ARRAYs.
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#57 Refactor the CI scripts for Bazel and CMake.
  ci/kokoro/Dockerfile.fedora-install
  ci/kokoro/cmake/README.md
  ci/kokoro/cmake/installed-dependencies/build.sh
  ci/kokoro/cmake/installed-dependencies/create-docker-image.sh
  ci/kokoro/create-docker-image.sh
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/cmake-presubmit.cfg
  ci/kokoro/docker/cmake.cfg
  ci/retry-command.sh
Labels: cla: yes

#63 Make spanner::Value::is_null() a template
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#66 Do not use storage_client in CMake.
  google/cloud/spanner/CMakeLists.txt
Labels: cla: yes, type: cleanup

#64 Create file to support super-builds and test them.
  ci/kokoro/Dockerfile.ubuntu
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/cmake-super-presubmit.cfg
  ci/kokoro/docker/cmake-super.cfg
  ci/super/CMakeLists.txt
  cmake/external/c-ares.cmake
  cmake/external/crc32c.cmake
  cmake/external/curl.cmake
  cmake/external/external-project-helpers.cmake
  cmake/external/google-cloud-cpp.cmake
  cmake/external/googletest.cmake
  cmake/external/grpc.cmake
  cmake/external/protobuf.cmake
  cmake/external/ssl.cmake
  cmake/external/zlib.cmake
  doc/setup-cmake-environment.md
Labels: cla: yes

#69 Adds support for optional<T>.
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#70 Update googleapis for CMake.
  ci/kokoro/Dockerfile.fedora-install
  cmake/external/google-cloud-cpp.cmake
  google/cloud/spanner/spanner_tool.cc
Labels: cla: yes, type: cleanup

#67 Enable clang-tidy and -Werror.
  .clang-tidy
  ci/kokoro/Dockerfile.fedora-install
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  cmake/EnableClangTidy.cmake
  cmake/EnableWerror.cmake
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#71 Add support for Doxygen and run it in a build.
  ci/kokoro/Dockerfile.fedora-install
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  cmake/EnableDoxygen.cmake
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/value.h
Labels: cla: yes, type: docs

#74 Use an array for the `docker run` arguments.
  ci/kokoro/docker/build.sh
Labels: cla: yes, type: cleanup

#75 Simplify instructions for vcpkg.
  doc/setup-cmake-environment.md
Labels: cla: yes, type: cleanup

#76 Cleanup: Prefer GetType() over type_.set_code; MakeNull is now a non-member
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#77 Refactored c'tor bodies to MakeValueProto() function.
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
Labels: cla: yes

#79 Support builds with the MemorySanitizer.
  .bazelrc
  ci/kokoro/Dockerfile.fedora-libcxx-msan
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/msan-presubmit.cfg
  ci/kokoro/docker/msan.cfg
Labels: cla: yes

#84 Update google-cloud-cpp.
  bazel/google_cloud_cpp_spanner_deps.bzl
  ci/kokoro/Dockerfile.fedora-install
  cmake/external/google-cloud-cpp.cmake
  google/cloud/spanner/spanner_version_test.cc
  google/cloud/spanner/version.cc
Labels: cla: yes

#83 Support building with gcc-4.8.
  ci/kokoro/Dockerfile.centos
  ci/kokoro/docker/build.sh
Labels: cla: yes

#85 Add Kokoro config files.
  ci/kokoro/docker/gcc-4.8-presubmit.cfg
  ci/kokoro/docker/gcc-4.8.cfg
Labels: cla: yes

#86 Run all the formatters in the clang-tidy build.
  ci/kokoro/Dockerfile.fedora-install
  ci/kokoro/docker/build-in-docker-cmake.sh
  cmake/EnableClangTidy.cmake
  cmake/EnableDoxygen.cmake
  cmake/EnableWerror.cmake
Labels: cla: yes

#87 Add the package for "shellcheck"
  ci/check-style.sh
  ci/kokoro/Dockerfile.fedora-install
  ci/kokoro/docker/build-in-docker-cmake.sh
Labels: cla: yes

#90 Add build with C++17 turned on.
  CMakeLists.txt
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/cxx17-presubmit.cfg
  ci/kokoro/docker/cxx17.cfg
Labels: cla: yes

#88 Adds Spanner STRUCT support to Value
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#94 Some cleanup from post-merge comments from PR #88
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
Labels: cla: yes

#92 Static assert that vector of vector is not allowed.
  google/cloud/spanner/value.h
Labels: cla: yes

#95 Allows Value construct from int and string literals.
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#96 Simplifies the Value constructor implementations.
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
Labels: cla: yes

#97 cleanup: Mark uncommon CMake options as "advanced".
  cmake/EnableClangTidy.cmake
Labels: cla: yes, type: cleanup

#98 Add the build badges to the top-level README.
  README.md
Labels: cla: yes

#100 Support Clang-3.8 build.
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/clang-3.8-presubmit.cfg
  ci/kokoro/docker/clang-3.8.cfg
Labels: cla: yes

#106 Automatically upload documentation to github.io
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/clang-tidy.cfg
  ci/kokoro/docker/upload-docs.sh
Labels: cla: yes

#108 Discover the actual branch in Kokoro.
  ci/kokoro/docker/upload-docs.sh
Labels: cla: yes

#110 Fix typo in link.
  doc/doxygen-style-guide.md
Labels: cla: yes

#109 Support code coverage builds.
  .codecov.yml
  CMakeLists.txt
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/coverage-presubmit.cfg
  ci/kokoro/docker/coverage.cfg
  ci/kokoro/docker/upload-coverage.sh
  cmake/EnableCoverage.cmake
Labels: cla: yes

#111 Row skeleton
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/row.h
  google/cloud/spanner/row_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#113 chore: Update google-cloud-cpp to version that installs googleapis proto files
  bazel/google_cloud_cpp_spanner_deps.bzl
  cmake/external/google-cloud-cpp.cmake
Labels: cla: yes

#114 fix: Fully qualify the namespace for ThrowInvalidArgument()
  google/cloud/spanner/value.h
Labels: cla: yes

#116 cleanup: Simplify creation of version_info.h
  google/cloud/spanner/BUILD
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_version.bzl
  google/cloud/spanner/version_info.h
Labels: cla: yes, type: cleanup

#117 cleanup: Make clang-format put the spanner headers first.
  .clang-format
  google/cloud/spanner/spanner_version_test.cc
  google/cloud/spanner/value.h
Labels: cla: yes

#118 Run integration tests in code coverage build.
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/coverage-presubmit.cfg
  ci/kokoro/docker/coverage.cfg
Labels: cla: yes

#121 Implement basic Stub for DatabaseAdmin.
  bazel/googleapis.BUILD
  google/cloud/spanner/BUILD
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/client_options.cc
  google/cloud/spanner/client_options.h
  google/cloud/spanner/client_options_test.cc
  google/cloud/spanner/internal/database_admin_stub.cc
  google/cloud/spanner/internal/database_admin_stub.h
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
  google/cloud/spanner/spanner_tool.cc
Labels: cla: yes

#124 bug: Add options to spanner tool
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/spanner_tool.cc
Labels: cla: yes

#115 Implement relational ops for spanner::Row
  google/cloud/spanner/row.h
  google/cloud/spanner/row_test.cc
Labels: cla: yes

#125 feat: Implement skeleton for DatabaseAdminClient.
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/database_admin_client.cc
  google/cloud/spanner/database_admin_client.h
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_tool.cc
Labels: cla: yes

#131 Added ToProto/FromProto support for Value
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#133 cleanup: DatabaseAdminStub functions are pure virtual.
  google/cloud/spanner/internal/database_admin_stub.cc
  google/cloud/spanner/internal/database_admin_stub.h
Labels: cla: yes, type: cleanup

#136 Disables forwarding c'tor if T == Row.
  google/cloud/spanner/row.h
  google/cloud/spanner/row_test.cc
Labels: cla: yes

#137 fix: Value::GetValue(optional<T>, ...) must check for nullness
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#139 Updates version of google-cloud-cpp dep.
  bazel/google_cloud_cpp_spanner_deps.bzl
  ci/kokoro/Dockerfile.fedora-install
  cmake/external/google-cloud-cpp.cmake
Labels: cla: yes

#134 doc: Fix documentation for DatabaseAdminClient.
  google/cloud/spanner/database_admin_client.h
Labels: cla: yes, type: docs

#140 feat: Added parameter support
  google/cloud/spanner/sql_statement.cc
  google/cloud/spanner/sql_statement.h
  google/cloud/spanner/sql_statement_test.cc
Labels: cla: yes

#135 feat: Implement unit tests for DatabaseAdminClient.
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/database_admin_client.h
  google/cloud/spanner/database_admin_client_test.cc
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#142 Add an abstraction layer for string <=> std::tm conversions
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/README.md
  google/cloud/spanner/internal/time_format.cc
  google/cloud/spanner/internal/time_format.h
  google/cloud/spanner/internal/time_format_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#130 feat: Implement skeleton SpannerStub
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/spanner_stub.cc
  google/cloud/spanner/internal/spanner_stub.h
  google/cloud/spanner/internal/spanner_stub_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#143 Introduce google::cloud::spanner::Date to represent a Spanner DATE
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/date.h
  google/cloud/spanner/date_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#144 Add support for converting Spanner DATE values to/from strings
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/date.cc
  google/cloud/spanner/internal/date.h
  google/cloud/spanner/internal/date_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#147 Add support for converting Spanner TIMESTAMP values to/from strings
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/time.cc
  google/cloud/spanner/internal/time.h
  google/cloud/spanner/internal/time_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#149 feat: Implement spanner::Value support for TIMESTAMP and DATE
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#148 bug: Fix flake in DatabaseAdminClient unit test.
  google/cloud/spanner/database_admin_client.cc
Labels: cla: yes

#146 Iterate tuple
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/tuple_utils.h
  google/cloud/spanner/internal/tuple_utils_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
  google/cloud/spanner/value.h
Labels: cla: yes

#150 Document the return value of ParseTime()
  google/cloud/spanner/internal/time_format.cc
  google/cloud/spanner/internal/time_format.h
Labels: cla: yes

#151 Removes need for tuple-like types to overload ADL `get<I>(T)`.
  google/cloud/spanner/internal/tuple_utils.h
  google/cloud/spanner/internal/tuple_utils_test.cc
Labels: cla: yes

#152 Makes Value::GetValue() return StatusOr<T>
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#153 Adds ParseRow() function
  google/cloud/spanner/row.h
  google/cloud/spanner/row_test.cc
Labels: cla: yes

#154 cleanup: Make .clang-tidy consistent.
  .clang-tidy
  google/cloud/spanner/version.cc
Labels: cla: yes, type: cleanup

#155 cleanup: Test extracting non-null optionals.
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#156 feat: Add a default c'tor for Value
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#158 chore: Update google-cloud-cpp dep version.
  bazel/google_cloud_cpp_spanner_deps.bzl
  ci/kokoro/Dockerfile.fedora-install
  cmake/external/google-cloud-cpp.cmake
Labels: cla: yes

#159 feat: Made Row::size() member static.
  google/cloud/spanner/row.h
  google/cloud/spanner/row_test.cc
Labels: cla: yes
