Repository googleapis/google-cloud-cpp-spanner, pull requests merged in 2019-07, with the labels that each got.

#165 Remove dependency on bigtable_client.
  bazel/google_cloud_cpp_spanner_deps.bzl
  bazel/googleapis.BUILD
  ci/kokoro/Dockerfile.fedora-install
  cmake/external/google-cloud-cpp.cmake
  google/cloud/spanner/BUILD
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/database_admin_client.cc
  google/cloud/spanner/integration_tests/BUILD
  google/cloud/spanner/internal/database_admin_stub.cc
  google/cloud/spanner/internal/spanner_stub.cc
Labels: cla: yes

#167 bug: Do not run integration tests in super-build.
  .cmake-format.py
  ci/super/CMakeLists.txt
Labels: cla: yes

#162 feat: Implement retry loop for gRPC requests.
  cmake/EnableDoxygen.cmake
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/backoff_policy.h
  google/cloud/spanner/database_admin_client.cc
  google/cloud/spanner/internal/database_admin_retry.cc
  google/cloud/spanner/internal/database_admin_retry.h
  google/cloud/spanner/internal/retry_loop.cc
  google/cloud/spanner/internal/retry_loop.h
  google/cloud/spanner/internal/retry_loop_test.cc
  google/cloud/spanner/retry_policy.h
  google/cloud/spanner/retry_policy_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#168 Use EXPECT_STATUS_OK in integration test
  bazel/google_cloud_cpp_spanner_deps.bzl
  ci/kokoro/Dockerfile.fedora-install
  cmake/external/google-cloud-cpp.cmake
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/integration_tests/CMakeLists.txt
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
  google/cloud/spanner/internal/retry_loop_test.cc
Labels: cla: yes

#169 feat: Use a fixed type for TIMESTAMP
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/time.cc
  google/cloud/spanner/internal/time.h
  google/cloud/spanner/internal/time_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/timestamp.h
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#171 Add RowParser
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/row_parser.h
  google/cloud/spanner/row_parser_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#172 fix: RowParser consumes Values from functor, not input range
  google/cloud/spanner/row_parser.h
  google/cloud/spanner/row_parser_test.cc
Labels: cla: yes

#173 Improved some doxygen commenting.
  google/cloud/spanner/row.h
  google/cloud/spanner/value.h
Labels: cla: yes

#174 feat: Use policies to control polling.
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/database_admin_client.cc
  google/cloud/spanner/database_admin_client_test.cc
  google/cloud/spanner/internal/database_admin_retry.cc
  google/cloud/spanner/internal/database_admin_retry.h
  google/cloud/spanner/internal/database_admin_stub.cc
  google/cloud/spanner/internal/database_admin_stub.h
  google/cloud/spanner/internal/polling_loop.h
  google/cloud/spanner/internal/polling_loop_test.cc
  google/cloud/spanner/polling_policy.h
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes, type: feature request

#175 feat: Implement examples for DatabaseAdminClient.
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/database_admin_client.h
  google/cloud/spanner/examples/BUILD
  google/cloud/spanner/examples/CMakeLists.txt
  google/cloud/spanner/examples/database_admin_snippets.cc
  google/cloud/spanner/examples/spanner_client_examples.bzl
Labels: cla: yes, type: feature request

#176 feat: implement SqlPartition
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
  google/cloud/spanner/sql_partition.cc
  google/cloud/spanner/sql_partition.h
  google/cloud/spanner/sql_partition_test.cc
Labels: cla: yes

#199 Standardize naming: examples vs samples vs snippets
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/database_admin_client.h
  google/cloud/spanner/samples/BUILD
  google/cloud/spanner/samples/CMakeLists.txt
  google/cloud/spanner/samples/database_admin_samples.cc
  google/cloud/spanner/samples/spanner_client_samples.bzl
Labels: cla: yes

#201 cleanup: Support metadata as result in PollingLoop.
  google/cloud/spanner/internal/database_admin_retry.cc
  google/cloud/spanner/internal/polling_loop.h
  google/cloud/spanner/internal/polling_loop_test.cc
Labels: cla: yes

#197 feat: Add CMake install target.
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/install/Dockerfile.fedora
  ci/kokoro/install/build.sh
  ci/kokoro/install/common.cfg
  ci/kokoro/install/fedora-presubmit.cfg
  ci/kokoro/install/fedora.cfg
  ci/test-install/CMakeLists.txt
  ci/test-install/spanner_install_test.cc
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/config-version.cmake.in
  google/cloud/spanner/config.cmake.in
  google/cloud/spanner/config.pc.in
Labels: cla: yes

#203 feat: Implement DatabaseAdmin::UpdateDatabase.
  google/cloud/spanner/database_admin_client.cc
  google/cloud/spanner/database_admin_client.h
  google/cloud/spanner/database_admin_client_test.cc
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
  google/cloud/spanner/internal/database_admin_retry.cc
  google/cloud/spanner/internal/database_admin_retry.h
  google/cloud/spanner/internal/database_admin_stub.cc
  google/cloud/spanner/internal/database_admin_stub.h
  google/cloud/spanner/samples/database_admin_samples.cc
Labels: cla: yes, type: feature request

#214 feat: Adds Row::values() accessor that returns std::array<Value, N>
  google/cloud/spanner/row.h
  google/cloud/spanner/row_test.cc
Labels: cla: yes

#220 Update Bazel to 0.28.0
  bazel/google_cloud_cpp_spanner_deps.bzl
  ci/install-bazel.sh
Labels: cla: yes

#219 feat: Add build for testing spanner as a bazel dependency.
  .gitignore
  ci/kokoro/bazel-dependency/linux/build.sh
  ci/kokoro/bazel-dependency/linux/continuous.cfg
  ci/kokoro/bazel-dependency/linux/presubmit.cfg
  ci/test-install/BUILD
  ci/test-install/WORKSPACE
Labels: cla: yes

#212 feat: Implement Mutations skeleton.
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/mutations.cc
  google/cloud/spanner/mutations.h
  google/cloud/spanner/mutations_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes, type: feature request

#216 Add equality operators to SqlStatement class
  google/cloud/spanner/sql_statement.h
  google/cloud/spanner/sql_statement_test.cc
Labels: cla: yes

#204 chore: Speedup install builds.
  .dockerignore
Labels: cla: yes

#227 chore: Add unit test to show that `Row` works with nulls (unset optionals)
  google/cloud/spanner/row_test.cc
Labels: cla: yes

#223 feat: Implement InsertOrUpdate and Replace mutations.
  google/cloud/spanner/mutations.h
  google/cloud/spanner/mutations_test.cc
Labels: cla: yes, type: feature request

#230 feat: Require a table name in mutation builders.
  google/cloud/spanner/mutations.h
  google/cloud/spanner/mutations_test.cc
Labels: cla: yes

#231 feat: Separate AddRow vs. EmplaceRow.
  google/cloud/spanner/mutations.h
  google/cloud/spanner/mutations_test.cc
Labels: cla: yes

#233 bug: Always require column names for mutations.
  google/cloud/spanner/mutations.h
  google/cloud/spanner/mutations_test.cc
Labels: cla: yes

#235 Make EmplaceRow forward to AddRow
  google/cloud/spanner/mutations.h
Labels: cla: yes

#232 feat: Add support for Row<Value>
  google/cloud/spanner/row.h
  google/cloud/spanner/row_test.cc
Labels: cla: yes

#234 doc: Fix Doxygen formatting.
  google/cloud/spanner/database_admin_client.h
Labels: cla: yes, type: docs

#226 fix: RowParser accepts shared_ptr<ValueSource>
  google/cloud/spanner/row_parser.h
  google/cloud/spanner/row_parser_test.cc
Labels: cla: yes

#229 Add a sample for creating a struct with data
  google/cloud/spanner/database_admin_client.h
  google/cloud/spanner/samples/CMakeLists.txt
  google/cloud/spanner/samples/samples.cc
  google/cloud/spanner/samples/spanner_client_samples.bzl
Labels: cla: yes

#236 fix: RowParser improvements
  google/cloud/spanner/row_parser.h
  google/cloud/spanner/row_parser_test.cc
Labels: cla: yes

#240 chore: Update google cloud cpp version
  bazel/google_cloud_cpp_spanner_deps.bzl
  ci/kokoro/Dockerfile.fedora-install
  ci/kokoro/install/Dockerfile.fedora
  cmake/external/google-cloud-cpp.cmake
Labels: cla: yes

#241 cleanup: Enforce formatting on all Bazel files.
  bazel/googleapis.BUILD
  ci/check-style.sh
  ci/test-install/WORKSPACE
Labels: cla: yes

#243 cleanup: Tweak .gitignore file.
  .gitignore
Labels: cla: yes

#242 Clarified docs about a default constructed Value.
  google/cloud/spanner/value.h
Labels: cla: yes

#221 feat: implement `ResultSet`.
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/result_set.h
  google/cloud/spanner/result_set_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#247 feat: Create landing page for reference docs.
  google/cloud/spanner/doc/spanner-main.dox
Labels: cla: yes

#248 fix: RowParser now behaves better and only consumes a Value when it must
  google/cloud/spanner/row_parser.h
  google/cloud/spanner/row_parser_test.cc
Labels: cla: yes

#250 bug: Add CMAKE_PREFIX_PATH to external/curl.cmake
  cmake/external/curl.cmake
Labels: cla: yes

#215 feat: Implement google::cloud::spanner::Transaction
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/transaction_impl.cc
  google/cloud/spanner/internal/transaction_impl.h
  google/cloud/spanner/internal/transaction_impl_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
  google/cloud/spanner/transaction.cc
  google/cloud/spanner/transaction.h
  google/cloud/spanner/transaction_test.cc
Labels: cla: yes

#253 Add support to generate compile_commands.json file
  .gitignore
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
Labels: cla: yes

#255 feat: Add `internal::Base64Encode()` and `internal::Base64Decode()`
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/base64.cc
  google/cloud/spanner/internal/base64.h
  google/cloud/spanner/internal/base64_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#256 Revert "Add support to generate compile_commands.json file (#253)"
  .gitignore
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
Labels: cla: yes

#258 chore: Add build that runs with exceptions disabled
  CMakeLists.txt
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  cmake/EnableCxxExceptions.cmake
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/transaction_impl_test.cc
Labels: cla: yes

#260 Fix some compile warnings with clang 3.8
  google/cloud/spanner/row.h
  google/cloud/spanner/row_test.cc
Labels: cla: yes

#259 Silence shellcheck warning.
  ci/kokoro/docker/build-in-docker-cmake.sh
Labels: cla: yes

#257 feat: Added Value::Bytes support
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#261 fix: some compile warnings with clang 3.8
  google/cloud/spanner/internal/base64.cc
Labels: cla: yes

#263 fix: added empty .cfg files for noex build
  ci/kokoro/docker/noex-presubmit.cfg
  ci/kokoro/docker/noex.cfg
Labels: cla: yes

#252 feat: give SqlPartition equality support
  google/cloud/spanner/sql_partition.cc
  google/cloud/spanner/sql_partition.h
  google/cloud/spanner/sql_partition_test.cc
Labels: cla: yes

#251 feat: add MergeChunk() function for "unchunking" incoming Values
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/merge_chunk.cc
  google/cloud/spanner/internal/merge_chunk.h
  google/cloud/spanner/internal/merge_chunk_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#266 Migrate from __EXCEPTIONS to GOOGLE_CLOUD_CPP_HAVE_EXCEPTIONS
  google/cloud/spanner/internal/transaction_impl.h
  google/cloud/spanner/internal/transaction_impl_test.cc
Labels: cla: yes

#269 Add a CommitResult type.
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/commit_result.h
  google/cloud/spanner/spanner_client.bzl
Labels: cla: yes

#265 cleanup: Factor out IsProtoEqual gmock matcher
  google/cloud/spanner/BUILD
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/merge_chunk_test.cc
  google/cloud/spanner/mutations_test.cc
  google/cloud/spanner/spanner_client_testing.bzl
  google/cloud/spanner/testing/matchers.h
Labels: cla: yes

#274 Update include guards to use correct repo name
  ci/check-include-guards.gawk
  google/cloud/spanner/backoff_policy.h
  google/cloud/spanner/client_options.h
  google/cloud/spanner/commit_result.h
  google/cloud/spanner/database_admin_client.h
  google/cloud/spanner/date.h
  google/cloud/spanner/internal/base64.h
  google/cloud/spanner/internal/database_admin_retry.h
  google/cloud/spanner/internal/database_admin_stub.h
  google/cloud/spanner/internal/date.h
  google/cloud/spanner/internal/merge_chunk.h
  google/cloud/spanner/internal/polling_loop.h
  google/cloud/spanner/internal/retry_loop.h
  google/cloud/spanner/internal/spanner_stub.h
  google/cloud/spanner/internal/time.h
  google/cloud/spanner/internal/time_format.h
  google/cloud/spanner/internal/transaction_impl.h
  google/cloud/spanner/internal/tuple_utils.h
  google/cloud/spanner/mutations.h
  google/cloud/spanner/polling_policy.h
  google/cloud/spanner/result_set.h
  google/cloud/spanner/retry_policy.h
  google/cloud/spanner/row.h
  google/cloud/spanner/row_parser.h
  google/cloud/spanner/sql_partition.h
  google/cloud/spanner/sql_statement.h
  google/cloud/spanner/testing/matchers.h
  google/cloud/spanner/timestamp.h
  google/cloud/spanner/transaction.h
  google/cloud/spanner/value.h
  google/cloud/spanner/version.h
  google/cloud/spanner/version_info.h
  google/cloud/spanner/version_info.h.in
Labels: cla: yes
