Repository googleapis/google-cloud-cpp-spanner, pull requests merged in 2019-08, with the labels that each got.

#280 testing: Run integration tests in parallel
  ci/kokoro/docker/build-in-docker-cmake.sh
Labels: cla: yes

#276 feat: Skeleton for spanner::Client
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#282 Added warning not to work on BatchDML until after Alpha. [skip ci]
  google/cloud/spanner/client.cc
Labels: cla: yes

#290 fixed indenting
  google/cloud/spanner/client.cc
Labels: cla: yes

#291 cleanup: Fix a few doxygen nits.
  google/cloud/spanner/client.h
Labels: cla: yes, type: cleanup

#295 Supply the database name when creating a Client.
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
Labels: cla: yes

#275 Add normalization to `google::cloud::spanner::Date`
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/date.cc
  google/cloud/spanner/date.h
  google/cloud/spanner/date_test.cc
  google/cloud/spanner/spanner_client.bzl
Labels: cla: yes

#300 Implement `MakeReadOnlyTransaction()` and `MakeReadWriteTransaction()`
  google/cloud/spanner/transaction.h
  google/cloud/spanner/transaction_test.cc
Labels: cla: yes

#299 Reimplement `DateToString()` and `DateFromString()`
  google/cloud/spanner/internal/date.cc
  google/cloud/spanner/internal/date_test.cc
Labels: cla: yes

#297 feat: Create configuration for macOS+Bazel build.
  .gitignore
  ci/kokoro/macos/bazel.cfg
  ci/kokoro/macos/build-bazel.sh
  ci/kokoro/macos/build-cmake.sh
  ci/kokoro/macos/build.sh
  ci/kokoro/macos/cmake-super-presubmit.cfg
  ci/kokoro/macos/cmake-super.cfg
  ci/kokoro/macos/common.cfg
Labels: cla: yes

#292 cleanup: Refactor RandomDatabaseName() function.
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/integration_tests/BUILD
  google/cloud/spanner/integration_tests/CMakeLists.txt
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
  google/cloud/spanner/spanner_client_testing.bzl
  google/cloud/spanner/testing/random_database_name.cc
  google/cloud/spanner/testing/random_database_name.h
Labels: cla: yes

#304 bug: Fix Bazel presubmit configuration.
  .gitignore
  ci/kokoro/macos/bazel-presubmit.cfg
Labels: cla: yes

#308 cleanup: Fix shellcheck warning.
  ci/kokoro/macos/build-bazel.sh
Labels: cla: yes

#303 bug: Fix macOS+CMake build.
  ci/kokoro/macos/build-cmake.sh
  ci/kokoro/macos/build.sh
Labels: cla: yes

#309 bug: Install dependencies on Kokoro.
  ci/kokoro/macos/build-cmake.sh
Labels: cla: yes

#302 feat: Implement spanner::Client::Commit.
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/integration_tests/CMakeLists.txt
  google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
  google/cloud/spanner/integration_tests/spanner_client_integration_tests.bzl
  google/cloud/spanner/mutations.h
Labels: cla: yes

#313 feat: Generalize internal::Visit(Transaction).
  google/cloud/spanner/client.cc
  google/cloud/spanner/internal/transaction_impl.h
  google/cloud/spanner/transaction.h
  google/cloud/spanner/transaction_test.cc
Labels: cla: yes, type: feature request

#315 fix: Removed redundant/confusing parts of Value API
  google/cloud/spanner/row_test.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#318 fix: Use 4-digit year for consistency
  google/cloud/spanner/internal/compiler_info.cc
Labels: cla: yes

#314 feat: Add a PartialResultSetReader class.
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/partial_result_set_reader.cc
  google/cloud/spanner/internal/partial_result_set_reader.h
  google/cloud/spanner/internal/partial_result_set_reader_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#320 feat: Add Client -> Connection layer
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/connection.h
  google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl.h
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/spanner_stub.cc
  google/cloud/spanner/internal/spanner_stub.h
  google/cloud/spanner/internal/spanner_stub_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#325 fix: Use long long literals for MSVC compiler.
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#324 fix: Add a ref-qualifier for correct overload
  google/cloud/spanner/row.h
Labels: cla: yes

#326 testing: Add Windows Bazel build
  bazel/google_cloud_cpp_spanner_deps.bzl
  ci/kokoro/windows/bazel/build.bat
  ci/kokoro/windows/bazel/common.cfg
  ci/kokoro/windows/bazel/continuous.cfg
  ci/kokoro/windows/bazel/presubmit.cfg
Labels: cla: yes

#327 feat: Add a stub `KeySet` class.
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/keys.h
  google/cloud/spanner/keys_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#317 feat: add KeyRange and KeySet classes
  google/cloud/spanner/keys.h
  google/cloud/spanner/keys_test.cc
Labels: cla: yes

#330 docs: Add a badge for Windows Bazel build
  README.md
Labels: cla: yes

#333 Cleaned up .clang-tidy file.
  .clang-tidy
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/database_admin_client_test.cc
  google/cloud/spanner/internal/build_info.cc.in
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/partial_result_set_reader_test.cc
  google/cloud/spanner/internal/retry_loop_test.cc
  google/cloud/spanner/internal/spanner_stub.cc
  google/cloud/spanner/result_set_test.cc
  google/cloud/spanner/spanner_version_test.cc
  google/cloud/spanner/sql_partition_test.cc
  google/cloud/spanner/testing/matchers.h
  google/cloud/spanner/value.cc
  google/cloud/spanner/version.cc
  google/cloud/spanner/version.h
Labels: cla: yes

#334 feat: let clang-tidy build not fail if there are edited files.
  ci/check-style.sh
  ci/kokoro/docker/build.sh
Labels: cla: yes

#332 Quash a clang-3.8 warning (suggest braces around initialization)
  google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
Labels: cla: yes

#319 Make the C++ mappings of orderable Spanner types also orderable
  google/cloud/spanner/date.h
  google/cloud/spanner/date_test.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#331 Provide an ordering to transaction visitors
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/transaction_impl.h
  google/cloud/spanner/internal/transaction_impl_test.cc
  google/cloud/spanner/transaction_test.cc
Labels: cla: yes

#335 Add a ToProto() method for SqlStatement.
  google/cloud/spanner/sql_statement.cc
  google/cloud/spanner/sql_statement.h
  google/cloud/spanner/sql_statement_test.cc
Labels: cla: yes

#337 Prefer static_assert() over std::enable_if<>
  google/cloud/spanner/internal/transaction_impl.h
Labels: cla: yes

#336 remove unnecessary explicit types from this test.
  google/cloud/spanner/internal/partial_result_set_reader_test.cc
Labels: cla: yes

#338 feat: Implement Client::Rollback()
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/connection.h
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl.h
  google/cloud/spanner/internal/connection_impl_test.cc
Labels: cla: yes

#341 Delete "makes clang-tidy angry" comments.
  google/cloud/spanner/database_admin_client_test.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/partial_result_set_reader_test.cc
  google/cloud/spanner/internal/retry_loop_test.cc
Labels: cla: yes

#343 Always use using-declarations for symbols in ::testing
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
  google/cloud/spanner/internal/build_info_test.cc
  google/cloud/spanner/internal/compiler_info_test.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/retry_loop_test.cc
Labels: cla: yes

#345 Remove KeySet placeholder in favor of the real thing
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
Labels: cla: yes

#340 feat: add type erased KeySet, KeySetBuilder::Build, and ToProto(KeySet)
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/keys.cc
  google/cloud/spanner/keys.h
  google/cloud/spanner/keys_test.cc
  google/cloud/spanner/spanner_client.bzl
Labels: cla: yes

#349 Enable clang-format proto raw string formatting.
  .clang-format
  google/cloud/spanner/internal/partial_result_set_reader_test.cc
  google/cloud/spanner/keys_test.cc
  google/cloud/spanner/mutations_test.cc
  google/cloud/spanner/sql_statement_test.cc
Labels: cla: yes

#348 feat: Implement spanner::MakeDeleteMutation()
  google/cloud/spanner/mutations.h
  google/cloud/spanner/mutations_test.cc
Labels: cla: yes

#350 feat: add Read and ExecuteSql methods
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_options.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/connection.h
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl.h
  google/cloud/spanner/internal/connection_impl_test.cc
Labels: cla: yes

#351 cleanup: Simplify (future) releases.
  CMakeLists.txt
  google/cloud/spanner/BUILD
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/build_info.cc.in
  google/cloud/spanner/internal/build_info.h
  google/cloud/spanner/internal/build_info_test.cc
  google/cloud/spanner/spanner_client_version.bzl
  google/cloud/spanner/spanner_version_test.cc
  google/cloud/spanner/version.cc
Labels: cla: yes, type: cleanup

#352 Misc small cleanups in client/connection:
  google/cloud/spanner/client.h
  google/cloud/spanner/connection.h
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl.h
Labels: cla: yes

#353 bug: Fix crashes in Client::Read and Client::ExecuteSql.
  google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/partial_result_set_reader.cc
  google/cloud/spanner/internal/partial_result_set_reader.h
  google/cloud/spanner/internal/partial_result_set_reader_test.cc
Labels: cla: yes, type: cleanup

#354 chore: Small style cleanup to keys.h
  google/cloud/spanner/keys.cc
  google/cloud/spanner/keys.h
Labels: cla: yes

#361 feat: Add integration test for DeleteMutation.
  .clang-tidy
  google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
Labels: cla: yes

#362 chore: Use KeySet proto as type-erased storage
  google/cloud/spanner/keys.cc
  google/cloud/spanner/keys.h
  google/cloud/spanner/keys_test.cc
Labels: cla: yes

#364 feat: Remove default construction from Bound and KeyRange
  google/cloud/spanner/keys.h
  google/cloud/spanner/keys_test.cc
Labels: cla: yes

#363 bug: PartialResultSet can have no row types.
  google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
  google/cloud/spanner/internal/partial_result_set_reader.cc
  google/cloud/spanner/internal/partial_result_set_reader_test.cc
Labels: cla: yes

#366 feat: Integration tests for Rollback().
  google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
  google/cloud/spanner/row.h
Labels: cla: yes

#367 feat: Implement logging stub for spanner.
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/client_options.cc
  google/cloud/spanner/client_options.h
  google/cloud/spanner/client_options_test.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/database_admin_stub.cc
  google/cloud/spanner/internal/logging_spanner_stub.cc
  google/cloud/spanner/internal/logging_spanner_stub.h
  google/cloud/spanner/internal/logging_spanner_stub_test.cc
  google/cloud/spanner/internal/spanner_stub.cc
  google/cloud/spanner/internal/spanner_stub.h
  google/cloud/spanner/internal/spanner_stub_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
  google/cloud/spanner/testing/matchers.h
  google/cloud/spanner/testing/mock_spanner_stub.h
Labels: cla: yes

#368 refactor: Single client for all MutateAndReadIntegrationTest cases
  google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
Labels: cla: yes

#365 feat: add KeySet equality operators and constructor from proto
  google/cloud/spanner/keys.cc
  google/cloud/spanner/keys.h
  google/cloud/spanner/keys_test.cc
Labels: cla: yes

#371 feat: added unit test for FromProto
  google/cloud/spanner/keys_test.cc
Labels: cla: yes

#372 Parallelize external builds
  ci/super/CMakeLists.txt
  cmake/external/c-ares.cmake
  cmake/external/crc32c.cmake
  cmake/external/curl.cmake
  cmake/external/external-project-helpers.cmake
  cmake/external/google-cloud-cpp.cmake
  cmake/external/googletest.cmake
  cmake/external/grpc.cmake
  cmake/external/protobuf.cmake
  cmake/external/zlib.cmake
Labels: cla: yes

#358 Implement spanner::RunTransaction() skeleton
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/integration_tests/mutate_and_read_integration_test.cc
Labels: cla: yes

#374 cleanup: Rename integration test.
  google/cloud/spanner/integration_tests/CMakeLists.txt
  google/cloud/spanner/integration_tests/client_integration_test.cc
  google/cloud/spanner/integration_tests/spanner_client_integration_tests.bzl
Labels: cla: yes

#376 feat: Implement integration tests for ExecuteSql.
  google/cloud/spanner/integration_tests/client_integration_test.cc
Labels: cla: yes

#373 feat: makes KeySetBuilder<T>::Build() more efficient with rvalue qualifier
  google/cloud/spanner/keys.h
  google/cloud/spanner/keys_test.cc
Labels: cla: yes

#375 Handle a response with no values.
  google/cloud/spanner/internal/partial_result_set_reader.cc
  google/cloud/spanner/internal/partial_result_set_reader_test.cc
Labels: cla: yes

#378 feat: Add dml_standard_insert sample code.
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#381 feat: Implement spanner_insert_data sample.
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes, type: feature request

#380 Make NextValue() std::move from the received value.
  google/cloud/spanner/internal/partial_result_set_reader.cc
Labels: cla: yes

#382 feat: Add `Database` class to encapsulate project_id, instance_id, database_id
  ci/test-install/spanner_install_test.cc
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/database.cc
  google/cloud/spanner/database.h
  google/cloud/spanner/database_admin_client.cc
  google/cloud/spanner/database_admin_client.h
  google/cloud/spanner/database_admin_client_test.cc
  google/cloud/spanner/database_test.cc
  google/cloud/spanner/integration_tests/client_integration_test.cc
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl.h
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/samples/samples.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#383 cleanup: Share spanner::Client across samples.
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#385 feat: Implement spanner_dml_standard_update sample.
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#391 feat: implement spanner_read_{only,write}_transaction samples.
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#393 Namespace tweaks for samples
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#384 feat: add ReadPartition files
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/client_options.h
  google/cloud/spanner/client_options_test.cc
  google/cloud/spanner/read_partition.cc
  google/cloud/spanner/read_partition.h
  google/cloud/spanner/read_partition_test.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#396 feat: implement delete samples.
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#394 Support chunked_value reassembly.
  google/cloud/spanner/internal/partial_result_set_reader.cc
  google/cloud/spanner/internal/partial_result_set_reader.h
  google/cloud/spanner/internal/partial_result_set_reader_test.cc
Labels: cla: yes

#399 feat: implement query_data_with_struct sample.
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#401 cleanup: Simplify spanner_update_data sample.
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#403 cleanup: Refactor common code in samples.
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#404 doc: Update README file badges and links.
  README.md
  ci/generate-badges.sh
Labels: cla: yes

#402 feat: Implement query_data_with_array_of_struct sample.
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#405 feat: A simpler quickstart program.
  google/cloud/spanner/doc/spanner-main.dox
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#410 cleanup: fix a shellcheck warning.
  ci/generate-badges.sh
Labels: cla: yes

#411 feat: Implement more Cloud Spanner STRUCT samples.
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#408 feat: implement PartitionRead and Read(ReadPartition)
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/connection.h
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl.h
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/read_partition.cc
  google/cloud/spanner/read_partition.h
  google/cloud/spanner/transaction.cc
  google/cloud/spanner/transaction.h
Labels: cla: yes

#397 Simplify Client::RunTransaction() functor interface
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/connection.h
  google/cloud/spanner/integration_tests/client_integration_test.cc
  google/cloud/spanner/mutations.h
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#434 chore: sanitizer builds should have debug symbols.
  .bazelrc
Labels: cla: yes

#406 bug: Make internal::ConnectionImpl thread-safe.
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl.h
  google/cloud/spanner/internal/connection_impl_test.cc
Labels: cla: yes

#437 chore: run coverage tests sequentially.
  ci/kokoro/docker/build-in-docker-cmake.sh
  google/cloud/spanner/row_test.cc
Labels: cla: yes

#473 Fix a header nit (cstdint vs cinttypes)
  google/cloud/spanner/testing/matchers.h
Labels: cla: yes

#476 chore: adjust code coverage exclusions.
  .codecov.yml
Labels: cla: yes

#488 bug: fix logging for streams.
  google/cloud/spanner/internal/logging_spanner_stub.cc
Labels: cla: yes

#471 feat: Implement a simple stress test.
  google/cloud/spanner/integration_tests/CMakeLists.txt
  google/cloud/spanner/integration_tests/client_stress_test.cc
  google/cloud/spanner/integration_tests/spanner_client_integration_tests.bzl
Labels: cla: yes

#501 feat: add Client::ExecuteBatchDml() with integration test
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/batch_dml_result.h
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/connection.h
  google/cloud/spanner/integration_tests/client_integration_test.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl.h
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/spanner_client.bzl
Labels: cla: yes

#475 test: Run unit tests on windows bazel build
  ci/kokoro/windows/bazel/build.bat
  google/cloud/spanner/connection_options_test.cc
Labels: cla: yes

#477 chore: sanitize the integration tests.
  ci/kokoro/docker/bazel-dependency-presubmit.cfg
  ci/kokoro/docker/bazel-dependency.cfg
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/common.cfg
  ci/kokoro/docker/coverage.cfg
  ci/kokoro/docker/integration-presubmit.cfg
  ci/kokoro/docker/integration.cfg
Labels: cla: yes

#510 bug: RunTransaction uses a time-based retry policy.
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
Labels: cla: yes

#513 bug: make rollback test less flaky.
  google/cloud/spanner/integration_tests/client_integration_test.cc
Labels: cla: yes

#509 feat: add metadata in all RPCs.
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/metadata_spanner_stub.cc
  google/cloud/spanner/internal/metadata_spanner_stub.h
  google/cloud/spanner/internal/metadata_spanner_stub_test.cc
  google/cloud/spanner/internal/spanner_stub.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_testing.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
  google/cloud/spanner/testing/validate_metadata.cc
  google/cloud/spanner/testing/validate_metadata.h
Labels: cla: yes
